feat: youtube api추가(완성x), gradle추가, yml에 유튜브api키 추가
EST-Backend-6th-WhereToGO/main_repo pull request #4
Opened 2024-12-04 08:10 UTC by gyuchanm

feat: youtube api추가(완성x), gradle추가, yml에 유튜브api키 추가

2024-12-04 08:12 UTC, anhyeongmin approved these changes

2024-12-04 08:59 UTC, anhyeongmin requested changes
.

2024-12-05 07:39 UTC, sodami-hub commented
okay~ good~

2024-12-05 07:40 UTC, sodami-hub submitted a review, later dismissed
ok good~

2024-12-05 08:41 UTC, anhyeongmin approved these changes

2024-12-05 08:42 UTC, seohyun96 commented
.

2024-12-05 08:43 UTC, seohyun96 approved these changes

2024-12-05 08:46 UTC, sodami-hub approved these changes

2024-12-05 08:47 UTC, merged